spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stats_db}
    username: ${SPRING_DATASOURCE_USERNAME:stats_user}
    password: ${SPRING_DATASOURCE_PASSWORD:stats_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  sql:
    init:
      mode: never

server:
  port: ${SERVER_PORT:9090}

logging:
  level:
    root: WARN
    ru.practicum: INFO
    org.springframework.web: INFO