spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/main_db}
    username: ${SPRING_DATASOURCE_USERNAME:main_user}
    password: ${SPRING_DATASOURCE_PASSWORD:main_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  sql:
    init:
      mode: never

server:
  port: ${SERVER_PORT:8080}

stats:
  server:
    url: ${STATS_SERVER_URL:http://localhost:9090}

logging:
  level:
    ru.practicum: INFO
    org.springframework: INFO
    org.hibernate.SQL: WARN