spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://main-db:5432/main_db
    username: main_user
    password: main_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080

stats:
  server:
    url: http://stats-server:9090