spring:
  application:
    name: ewm-main-service

  datasource:
    url: jdbc:postgresql://localhost:5432/main_db
    username: main_user
    password: main_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

stats:
  server:
    url: http://localhost:9090

logging:
  level:
    ru.practicum.ewm: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN